// Generated by CoffeeScript 1.8.0
(function() {
  describe('ngProgressbar', function() {
    var setup;
    setup = {};
    beforeEach(module('ProgressArc'));
    return beforeEach(inject(function($rootScope, $compile, $injector) {
      setup.elm = angular.element('<test defined="defined"></test>');
      setup.scope = $rootScope;
      setup.scope.defined = false;
      $compile(setup.elm)(setup.scope);
      return setup.scope.$digest();
    }));
  });


  /*
    it 'should not be initially defined', () ->
      expect(setup.elm.scope().$$childTail.isDefined()).toBe(false)
   */

}).call(this);
