// Generated by CoffeeScript 1.8.0
(function() {
  describe('Unit: ArcPropertiesController', function() {
    var mockvalues, setup;
    beforeEach(module('ProgressArc'));
    setup = {};
    beforeEach(inject(function($controller, $rootScope) {
      setup.scope = $rootScope.$new();
      return setup.ctrl = $controller('ArcPropertiesController', {
        $scope: setup.scope
      });
    }));
    mockvalues = [];
    it('ensure getAngle returns fraction of circle', function() {
      return expect(setup.scope.arcProperties.getAngle(setup.scope.arcProperties.actual)).toEqual(1.2 * Math.PI);
    });
    return it('ensure getColor returns colored class', function() {
      return expect(setup.scope.arcProperties.getClass(setup.scope.arcProperties.actual, setup.scope.arcProperties.expected)).toEqual('brightgreenarc');
    });
  });


  /*
  describe 'Integration/E2E Testing', () ->
  
      it 'ensure user can change actual and expected values', () ->
          
      it 'ensure actual arc and expected arc are visible', () ->
          
      it 'ensure percentage text is visible', () ->
   */

}).call(this);
